export const getAllEntries = () => {
  return [
    {
      key: '1',
      description: 'Padaria Asa Branca',
      location: {address: 'Rua Jandaia, 90'},
      entryAt: '27 set 9h',
      amount: 10,
      category: {color: '#3498db'},
    },
    {
      key: '2',
      description: 'Supermercado Isadora',
      location: {address: 'Rua Jandaia, 90'},
      entryAt: '27 out 9h',
      amount: 190,
      category: {color: '#9b59b6'},
    },
    {
      key: '3',
      description: 'Posto Ipiranga',
      location: {address: 'Rua Jandaia, 90'},
      entryAt: '27 nov 9h',
      amount: 12,
      category: {color: '#f1c40f'},
    },
    {
      key: '4',
      description: 'Posto Ipiranga',
      location: {address: 'Rua Jandaia, 90'},
      entryAt: '27 nov 9h',
      amount: 13,
      category: {color: '#f1c40f'},
    },
    {
      key: '5',
      description: 'Posto Ipiranga',
      location: {address: 'Rua Jandaia, 90'},
      entryAt: '27 nov 9h',
      amount: 14,
      category: {color: '#f1c40f'},
    },
    {
      key: '6',
      description: 'Posto Ipiranga',
      location: {address: 'Rua Jandaia, 90'},
      entryAt: '27 nov 9h',
      amount: 15,
      category: {color: '#f1c40f'},
    },
    {
      key: '7',
      description: 'Posto Ipiranga',
      location: {address: 'Rua Jandaia, 90'},
      entryAt: '27 nov 9h',
      amount: 16,
      category: {color: '#f1c40f'},
    },
    {
      key: '8',
      description: 'Posto Ipiranga',
      location: {address: 'Rua Jandaia, 90'},
      entryAt: '27 nov 9h',
      amount: 17,
      category: {color: '#f1c40f'},
    },
    {
      key: '9',
      description: 'Posto Ipiranga',
      location: {address: 'Rua Jandaia, 90'},
      entryAt: '27 nov 9h',
      amount: 18,
      category: {color: '#f1c40f'},
    },
    {
      key: '10',
      description: 'Posto Ipiranga',
      location: {address: 'Rua Jandaia, 90'},
      entryAt: '27 nov 9h',
      amount: 18,
      category: {color: '#f1c40f'},
    },
    {
      key: '11',
      description: 'Posto Ipiranga',
      location: {address: 'Rua Jandaia, 90'},
      entryAt: '27 nov 9h',
      amount: 18,
      category: {color: '#f1c40f'},
    },
    {
      key: '12',
      description: 'Posto Ipiranga',
      location: {address: 'Rua Jandaia, 90'},
      entryAt: '27 nov 9h',
      amount: 18,
      category: {color: '#f1c40f'},
    },
    {
      key: '13',
      description: 'Posto Ipiranga',
      location: {address: 'Rua Jandaia, 90'},
      entryAt: '27 nov 9h',
      amount: 18,
      category: {color: '#f1c40f'},
    },
    {
      key: '14',
      description: 'Posto Ipiranga',
      location: {address: 'Rua Jandaia, 90'},
      entryAt: '27 nov 9h',
      amount: 18,
      category: {color: '#f1c40f'},
    },
  ];
};
